//! CLI subcommand dispatch — extracted from main.rs for maintainability.

use rupoo::db::TaskRepo;
use rupoo::loop_engine::LoopConfig;
use rupoo::skill::SkillManager;
use rupoo::task::{finish_step, think_step, tool_call_step, wait_for_input_step, Plan};
use std::sync::Arc;
use tracing::info;

// ---------------------------------------------------------------------------
// Enum definitions (moved from main.rs)
// ---------------------------------------------------------------------------

/// Manage and install external tools (MCP servers, search engines, etc.)
#[derive(clap::Subcommand)]
pub enum ToolsAction {
    /// Install cortex-scout MCP server for web search + page extraction
    InstallCortexScout {
        /// Version to install (default: latest)
        #[arg(long)]
        version: Option<String>,
    },
    /// List installed tools and their status
    Status,
}

#[derive(clap::Subcommand)]
pub enum LoopAction {
    /// Start a new adaptive loop
    Start {
        /// Goal / task description
        goal: String,
        /// Max iterations (default: 10)
        #[arg(long, default_value_t = 10)]
        max_iterations: u32,
        /// Token budget limit
        #[arg(long)]
        token_budget: Option<u64>,
        /// Time budget in seconds
        #[arg(long)]
        time_budget: Option<u64>,
    },
    /// Show loop status
    Status {
        /// Loop ID
        id: String,
    },
    /// List all loops
    List {
        /// Maximum loops to show
        #[arg(long, default_value_t = 20)]
        limit: usize,
    },
    /// Pause a running loop
    Pause {
        /// Loop ID
        id: String,
    },
    /// Resume a paused loop
    Resume {
        /// Loop ID
        id: String,
    },
    /// Cancel a loop
    Cancel {
        /// Loop ID
        id: String,
    },
}

#[derive(clap::Subcommand)]
pub enum SkillAction {
    /// List available skills
    List,
    /// Show details of a specific skill
    Show {
        /// Skill name
        name: String,
    },
    /// Run a skill (convert to plan and execute)
    Run {
        /// Skill name
        name: String,
        /// Database path
        #[arg(long)]
        db: Option<String>,
    },
    /// Install the built-in skills
    InstallBuiltin,
    /// Learn a skill from a completed plan
    Learn {
        /// Plan ID to learn from
        plan_id: String,
        /// Name for the new skill
        name: String,
        /// Description (optional)
        #[arg(long, default_value = "Learned from completed plan")]
        description: String,
        /// Database path (default: $RUPOO_HOME/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
}

#[derive(clap::Subcommand)]
pub enum ConfigAction {
    /// Set a configuration value (e.g., set api_key.anthropic sk-ant-xxx)
    Set {
        /// Configuration key (e.g. "api_key.anthropic", "model.ollama.base_url")
        key: String,
        /// Value to set
        value: String,
        /// Database path (default: $RUPOO_HOME/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
    /// Get a configuration value
    Get {
        key: String,
        /// Database path (default: $RUPOO_HOME/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
    /// List all configuration values
    List {
        /// Database path (default: $RUPOO_HOME/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
}

#[derive(clap::Subcommand)]
pub enum GitAction {
    /// Show git status
    Status,
    /// Stage all changes and commit
    Commit {
        /// Commit message
        #[arg(long)]
        message: String,
        /// Optional task ID to reference
        #[arg(long)]
        task: Option<String>,
    },
    /// Create a GitHub PR
    Pr {
        /// PR title
        #[arg(long)]
        title: String,
        /// PR body (summary)
        #[arg(long, default_value = "Generated by Plan Executor Agent")]
        body: String,
    },
}

#[derive(clap::Subcommand)]
pub enum ModelAction {
    /// Show current LLM configuration
    Show,
    /// List available providers and their default models
    List,
    /// Set provider and optionally model (e.g., "anthropic/claude-sonnet-4")
    Set {
        /// Provider name, optionally with /model suffix
        target: Option<String>,
    },
}

#[derive(clap::Subcommand)]
pub enum SessionAction {
    /// List all plans
    List {
        /// Maximum plans to show (default: 10)
        #[arg(long, default_value_t = 10)]
        limit: usize,
    },
    /// Show plan details and steps
    Show {
        /// Plan ID
        id: String,
    },
    /// Resume execution of a plan
    Resume {
        /// Plan ID
        id: String,
        /// Database path for the plan
        #[arg(long, default_value = "agent.db")]
        db: String,
        /// Optional input for WaitForInput steps
        #[arg(long)]
        input: Option<String>,
    },
    /// Delete a plan and its checkpoints
    Delete {
        /// Plan ID
        id: String,
    },
    /// Delete completed/failed plans older than N days
    Prune {
        /// Age in days (default: 30)
        #[arg(long, default_value_t = 30)]
        days: u64,
    },
}

// ---------------------------------------------------------------------------
// CLI command dispatcher
// ---------------------------------------------------------------------------

pub async fn run_cmd(cmd: super::Commands) -> anyhow::Result<()> {
    match cmd {
        super::Commands::Gui { db: _ } => {
            #[cfg(feature = "gui")]
            {
                match rupoo::gui::inner::run_gui(None) {
                    Ok(_) => {}
                    Err(e) => {
                        anyhow::bail!("GUI error: {}", e);
                    }
                }
            }
            #[cfg(not(feature = "gui"))]
            {
                anyhow::bail!("GUI feature is not enabled. Build with --features gui");
            }
        }
        super::Commands::Run { task, db, input } => {
            let db = resolve_db(db);
            let (repo, agent, _tool_executor) = crate::build_engine::build_engine(&db).await?;
            crate::executor::execute_plan(&repo, &agent, &task, input.as_deref()).await?;
        }
        super::Commands::Git { action } => match action {
            GitAction::Status => {
                let repo = rupoo::git::GitRepo::open(".")?;
                let branch = repo.current_branch()?;
                let statuses = repo.status()?;
                println!("Branch: {branch}");
                println!("Status ({} files):", statuses.len());
                for s in &statuses {
                    println!("  [{:>15}] {}", s.status, s.path);
                }
            }
            GitAction::Commit { message, task } => {
                let repo = rupoo::git::GitRepo::open(".")?;
                let hash = if let Some(task_id) = task {
                    repo.commit_with_task_ref(&message, &task_id)?
                } else {
                    repo.commit_all(&message)?
                };
                println!("Committed {hash}: {message}");
            }
            GitAction::Pr { title, body } => {
                let url = rupoo::git::create_gh_pr(&title, &body)?;
                println!("PR created: {url}");
            }
        },
        super::Commands::Config { action } => match action {
            ConfigAction::Set { key, value, db } => {
                let db = resolve_db(db);
                let (repo, _agent, _tool_executor) = crate::build_engine::build_engine(&db).await?;
                repo.set_setting(&key, &value).await?;
                info!(key = %key, "configuration saved");
                if key.starts_with("api_key") {
                    let display: String = value.chars().take(8).collect();
                    println!("Set {key} = {display}...",);
                } else {
                    println!("Set {key} = {value}");
                }
            }
            ConfigAction::Get { key, db } => {
                let db = resolve_db(db);
                let (repo, _agent, _tool_executor) = crate::build_engine::build_engine(&db).await?;
                match repo.get_setting(&key).await? {
                    Some(value) => println!("{key} = {value}"),
                    None => println!("{key} is not set"),
                }
            }
            ConfigAction::List { db } => {
                let db = resolve_db(db);
                let (repo, _agent, _tool_executor) = crate::build_engine::build_engine(&db).await?;
                let settings = repo.list_settings().await?;
                if settings.is_empty() {
                    println!("No configuration set.");
                } else {
                    for (k, v) in &settings {
                        let display = if k.starts_with("api_key") {
                            let prefix: String = v.chars().take(8).collect();
                            format!("{prefix}...")
                        } else {
                            v.clone()
                        };
                        println!("  {k} = {display}");
                    }
                }
            }
        },
        super::Commands::Skills { action } => match action {
            SkillAction::List => {
                let manager = SkillManager::new(SkillManager::default_dir());
                let skills = manager.list_skills()?;
                println!("Available skills ({})", skills.len());
                for s in &skills {
                    let skill = manager.load_skill(s)?;
                    println!("  {:<20} {}", skill.name, skill.description);
                }
            }
            SkillAction::Show { name } => {
                let manager = SkillManager::new(SkillManager::default_dir());
                let skill = manager.load_skill(&name)?;
                println!("Name:        {}", skill.name);
                println!("Description: {}", skill.description);
                println!("Version:     {}", skill.version);
                println!("Triggers:    {:?}", skill.trigger);
                println!("Steps:");
                for (i, step) in skill.steps.iter().enumerate() {
                    println!("  [{i}] {step:?}");
                }
            }
            SkillAction::Run { name, db } => {
                let db = resolve_db(db);
                let manager = SkillManager::new(SkillManager::default_dir());
                let skill = manager.load_skill(&name)?;
                let plan = manager.skill_to_plan(&skill);
                let (repo, agent, _tool_executor) = crate::build_engine::build_engine(&db).await?;
                repo.save_plan(&plan).await?;
                info!(plan_id = %plan.id, skill = %name, "skill plan saved");
                print_plan_summary(&plan);
                crate::executor::execute_plan(&repo, &agent, &plan.id, None).await?;
            }
            SkillAction::InstallBuiltin => {
                SkillManager::install_builtin_skills()?;
                println!("Built-in skills installed successfully.");
            }
            SkillAction::Learn {
                plan_id,
                name,
                description,
                db,
            } => {
                let db = resolve_db(db);
                let repo = Arc::new(TaskRepo::new(&db)?);
                let plan = repo.load_plan(&plan_id).await?;
                let skill = SkillManager::plan_to_skill(&plan, &name, &description);
                let manager = SkillManager::new(SkillManager::default_dir());
                manager.save_skill(&skill)?;
                println!(
                    "Learned skill '{}' from plan '{}' ({} steps)",
                    name,
                    plan.name,
                    skill.steps.len()
                );
            }
        },
        super::Commands::Demo { db } => {
            let db = resolve_db(db);
            let (repo, agent, _tool_executor) = crate::build_engine::build_engine(&db).await?;

            let plan = Plan::new(
                "Demo Plan",
                vec![
                    think_step("Analyze the current project structure"),
                    tool_call_step("list_directory", serde_json::json!({"path": "."})),
                    think_step("Evaluate the directory listing results"),
                    wait_for_input_step("Do you want to continue with file reading?"),
                    tool_call_step("file_read", serde_json::json!({"path": "Cargo.toml"})),
                    think_step("Summarize findings from the Cargo.toml"),
                    tool_call_step(
                        "echo",
                        serde_json::json!({"message": "All steps completed successfully!"}),
                    ),
                    finish_step("Demo plan execution finished"),
                ],
            );

            repo.save_plan(&plan).await?;
            info!(plan_id = %plan.id, name = %plan.name, "demo plan saved");

            print_plan_summary(&plan);
            crate::executor::execute_plan(&repo, &agent, &plan.id, None).await?;
        }
        super::Commands::McpServer => {
            rupoo::mcp_server::run_mcp_server().await?;
        }
        super::Commands::Serve { db: _, port } => {
            println!(
                "  {} Server mode (port {port}) — development only. Not for production use.",
                console::style("⚠").yellow()
            );
            println!(
                "  {} Must bind to 127.0.0.1 and add auth before exposing.",
                console::style("→").dim()
            );
            tokio::signal::ctrl_c().await?;
        }
        super::Commands::Completions { shell } => {
            use clap::CommandFactory;
            let shell_name = shell.to_lowercase();
            let shell_type = match shell_name.as_str() {
                "bash" => clap_complete::Shell::Bash,
                "zsh" => clap_complete::Shell::Zsh,
                "fish" => clap_complete::Shell::Fish,
                "elvish" => clap_complete::Shell::Elvish,
                "powershell" => clap_complete::Shell::PowerShell,
                _ => {
                    anyhow::bail!(
                        "unsupported shell '{}'. Supported: bash, zsh, fish, elvish, powershell",
                        shell
                    );
                }
            };
            clap_complete::generate(
                shell_type,
                &mut super::Cli::command(),
                "rupoo",
                &mut std::io::stdout(),
            );
        }
        super::Commands::Status { short, db } => {
            let db = resolve_db(db);
            crate::cli::cmds::status::run(&db, short).await?;
        }
        super::Commands::Model { action, db } => {
            let db = resolve_db(db);
            crate::cli::cmds::model::run(&db, action).await?;
        }
        super::Commands::Session { action, db } => {
            let db = resolve_db(db);
            crate::cli::cmds::session::run(&db, action).await?;
        }
        super::Commands::Loops { action, db } => {
            let db = resolve_db(db);
            handle_loop_action(db, action).await?;
        }
        super::Commands::Tools { action } => {
            handle_tools_action(action).await?;
        }
        super::Commands::Doctor { fix } => {
            crate::cli::cmds::doctor::run(fix).await?;
        }
        super::Commands::Logs {
            follow,
            lines,
            level,
            prev,
        } => {
            crate::cli::cmds::logs::run(follow, lines, level.as_deref(), prev).await?;
        }
    }

    Ok(())
}

/// Resolve database path, defaulting to `$RUPOO_HOME/agent.db`.
fn resolve_db(db: Option<String>) -> String {
    db.unwrap_or_else(|| {
        crate::tracing_setup::data_dir()
            .join("agent.db")
            .to_string_lossy()
            .to_string()
    })
}

fn print_plan_summary(plan: &Plan) {
    println!("\n=== PLAN: {} ===", plan.name);
    println!("ID: {}", plan.id);
    println!("Steps:");
    for (i, step) in plan.steps.iter().enumerate() {
        let label = match step {
            rupoo::task::Step::Think { instruction, .. } => format!("THINK: {instruction}"),
            rupoo::task::Step::ToolCall {
                tool_name, params, ..
            } => {
                format!("TOOL: {tool_name} ({})", params)
            }
            rupoo::task::Step::WaitForInput { prompt, .. } => format!("WAIT: {prompt}"),
            rupoo::task::Step::Finish { summary, .. } => format!("FINISH: {summary}"),
            rupoo::task::Step::Exec { command, .. } => format!("EXEC: {command}"),
            rupoo::task::Step::HttpRequest { url, method, .. } => format!("HTTP: {method:?} {url}"),
            rupoo::task::Step::BrowserAction { action, .. } => format!("BROWSER: {action:?}"),
        };
        println!("  [{i}] {label}");
    }
    println!("==========================\n");
}

// ---------------------------------------------------------------------------
// Loop action handler (Loop Engineering Phase C)
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Tools action handler — install MCP servers, etc.
// ---------------------------------------------------------------------------

async fn handle_tools_action(action: ToolsAction) -> anyhow::Result<()> {
    match action {
        ToolsAction::InstallCortexScout { version } => {
            install_cortex_scout(version.as_deref()).await?;
        }
        ToolsAction::Status => {
            check_tools_status().await?;
        }
    }
    Ok(())
}

/// Install cortex-scout MCP server binary.
async fn install_cortex_scout(version: Option<&str>) -> anyhow::Result<()> {
    let rupoo_home = rupoo::config::rupoo_home();
    let bin_dir = rupoo_home.join("bin");
    std::fs::create_dir_all(&bin_dir)?;

    let ver = version.unwrap_or("3.3.7");
    let arch = if cfg!(target_arch = "aarch64") {
        "arm64"
    } else {
        "x86_64"
    };
    let os = if cfg!(target_os = "macos") {
        "macos"
    } else {
        "linux"
    };
    let filename = format!("cortex-scout-{ver}-{os}-{arch}.tar.gz");
    let url =
        format!("https://github.com/cortex-works/cortex-scout/releases/download/v{ver}/{filename}");

    let binary_name = if cfg!(target_os = "windows") {
        "cortex-scout-mcp.exe"
    } else {
        "cortex-scout-mcp"
    };
    let binary_path = bin_dir.join(binary_name);

    if binary_path.exists() {
        println!(
            "cortex-scout already installed at: {}",
            binary_path.display()
        );
        println!("  Run `rupoo tools install-cortex-scout` again to reinstall.");
        return Ok(());
    }

    println!("Downloading cortex-scout v{} for {}-{}...", ver, os, arch);
    println!("  URL: {}", url);

    // Download via reqwest
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(300))
        .build()?;
    let response = client.get(&url).send().await?;

    if !response.status().is_success() {
        anyhow::bail!("Download failed: HTTP {}", response.status());
    }

    let bytes = response.bytes().await?;
    let temp_dir = std::env::temp_dir().join(format!("cortex-scout-{ver}"));
    std::fs::create_dir_all(&temp_dir)?;
    let tarball_path = temp_dir.join(&filename);

    std::fs::write(&tarball_path, &bytes)?;
    println!("  Downloaded {} MB", bytes.len() / 1_048_576);

    // Extract tarball
    let file = std::fs::File::open(&tarball_path)?;
    let decoder = flate2::read::GzDecoder::new(file);
    let mut archive = tar::Archive::new(decoder);

    for entry in archive.entries()? {
        let mut entry = entry?;
        let path = entry.path()?.to_path_buf();
        if let Some(name) = path.file_name() {
            if name == binary_name {
                entry.unpack(&binary_path)?;
                break;
            }
        }
    }

    // Make executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&binary_path, std::fs::Permissions::from_mode(0o755))?;
    }

    println!("  Installed: {}", binary_path.display());

    // Write MCP config
    let config_path = rupoo_home.join("config.toml");
    let config_content = if config_path.exists() {
        std::fs::read_to_string(&config_path)?
    } else {
        String::new()
    };

    if !config_content.contains("[mcp.servers.cortex-scout]") {
        let mcp_config = format!(
            r#"
[mcp.servers.cortex-scout]
command = "{}"
args = []
env = {{ SEARCH_ENGINES = "google,bing,duckduckgo,brave" }}
"#,
            binary_path.display()
        );
        std::fs::write(&config_path, config_content + &mcp_config)?;
        println!("  Added to config: {}", config_path.display());
    } else {
        println!("  MCP config already exists in: {}", config_path.display());
    }

    println!("\n✅ cortex-scout installed! Restart rupoo to use it.");
    println!("  Agent will now have `web_search` and `web_fetch` tools via MCP.");

    // Cleanup
    let _ = std::fs::remove_dir_all(&temp_dir);

    Ok(())
}

/// Check status of installed tools.
async fn check_tools_status() -> anyhow::Result<()> {
    let rupoo_home = rupoo::config::rupoo_home();

    println!("Tools status:");
    println!();

    // Check cortex-scout
    let scout_path = rupoo_home.join("bin/cortex-scout-mcp");
    if scout_path.exists() {
        println!(
            "  ✅ cortex-scout     installed at: {}",
            scout_path.display()
        );
        // Check MCP config
        let config_path = rupoo_home.join("config.toml");
        if config_path.exists() {
            let content = std::fs::read_to_string(&config_path)?;
            if content.contains("cortex-scout") {
                println!("     MCP config:      configured");
            } else {
                println!(
                    "     MCP config:      NOT configured (run `rupoo tools install-cortex-scout`)"
                );
            }
        }
    } else {
        println!("  ❌ cortex-scout     not installed");
        println!("     Install: `rupoo tools install-cortex-scout`");
    }

    Ok(())
}

async fn handle_loop_action(db: String, action: LoopAction) -> anyhow::Result<()> {
    let (_repo, agent, _) = crate::build_engine::build_engine(&db).await?;
    let agent = Arc::new(agent);

    let engine = agent
        .loop_engine
        .as_ref()
        .ok_or_else(|| anyhow::anyhow!("loop engine not initialized"))?;

    match action {
        LoopAction::Start {
            goal,
            max_iterations,
            token_budget,
            time_budget,
        } => {
            let config = LoopConfig {
                max_iterations,
                token_budget,
                time_budget_secs: time_budget,
                autonomy_level: rupoo::loop_engine::AutonomyLevel::L4AutoCorrect,
                ..Default::default()
            };

            println!("Starting loop: \"{}\"", goal);
            println!("  Max iterations: {}", max_iterations);

            let loop_result = engine
                .start_loop(&goal, config, Arc::clone(&agent), agent.llm_gateway_ref())
                .await?;

            println!("\nLoop finished:");
            println!("  ID: {}", loop_result.id);
            println!("  Status: {:?}", loop_result.status);
        }

        LoopAction::Status { id } => {
            let l = engine.get_loop_status(&id).await?;
            println!("Loop: {}", l.id);
            println!("  Goal: \"{}\"", l.goal);
            println!("  Status: {:?}", l.status);
            println!(
                "  Config: max_iters={}, autonomy={:?}",
                l.config.max_iterations, l.config.autonomy_level
            );
        }

        LoopAction::List { limit } => {
            let loops = engine.list_loops(limit, 0).await?;
            if loops.is_empty() {
                println!("No loops found.");
            } else {
                println!("Loops:");
                for l in &loops {
                    println!(
                        "  {} | {:?} | \"{}\"",
                        &l.id[..8.min(l.id.len())],
                        l.status,
                        &l.goal[..60.min(l.goal.len())]
                    );
                }
            }
        }

        LoopAction::Pause { id } => {
            engine.pause_loop(&id).await?;
            println!("Loop {} paused.", id);
        }

        LoopAction::Resume { id } => {
            println!("Resuming loop {}...", id);
            let l = engine
                .resume_loop(&id, Arc::clone(&agent), agent.llm_gateway_ref())
                .await?;
            println!("  Status: {:?}", l.status);
        }

        LoopAction::Cancel { id } => {
            engine.cancel_loop(&id).await?;
            println!("Loop {} cancelled.", id);
        }
    }

    Ok(())
}
