use std::sync::Arc;

use clap::{Parser, Subcommand};
use tracing::info;

use rupoo::agent::safety::SafetyContext;
use rupoo::agent::Agent;
use rupoo::db::TaskRepo;
use rupoo::mcp::McpToolExecutor;
use rupoo::skill::SkillManager;
use rupoo::task::{finish_step, think_step, tool_call_step, wait_for_input_step, Plan};

mod cli;
mod tracing_setup;

/// Rupoo — AI-powered assistant for your terminal.
/// Run without subcommands to enter interactive mode.
#[derive(Parser)]
#[command(name = "rupoo", version = "0.2.0", about)]
struct Cli {
    /// Show debug-level logs on stderr.
    #[arg(long, global = true)]
    verbose: bool,

    /// Optional subcommand. If omitted, enters interactive TUI.
    #[command(subcommand)]
    command: Option<Commands>,
}

#[derive(Subcommand)]
enum SkillAction {
    /// List available skills
    List,
    /// Show details of a specific skill
    Show {
        /// Skill name
        name: String,
    },
    /// Run a skill (convert to plan and execute)
    Run {
        /// Skill name
        name: String,
        /// Database path
        #[arg(long)]
        db: Option<String>,
    },
    /// Install the built-in skills
    InstallBuiltin,
    /// Learn a skill from a completed plan
    Learn {
        /// Plan ID to learn from
        plan_id: String,
        /// Name for the new skill
        name: String,
        /// Description (optional)
        #[arg(long, default_value = "Learned from completed plan")]
        description: String,
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
}

#[derive(Subcommand)]
enum ConfigAction {
    /// Set a configuration value (e.g., set api_key.anthropic sk-ant-xxx)
    Set {
        /// Configuration key (e.g. "api_key.anthropic", "model.ollama.base_url")
        key: String,
        /// Value to set
        value: String,
    },
    /// Get a configuration value
    Get {
        key: String,
    },
    /// List all configuration values
    List,
}

#[derive(Subcommand)]
enum GitAction {
    /// Show git status
    Status,
    /// Stage all changes and commit
    Commit {
        /// Commit message
        #[arg(long)]
        message: String,
        /// Optional task ID to reference
        #[arg(long)]
        task: Option<String>,
    },
    /// Create a GitHub PR
    Pr {
        /// PR title
        #[arg(long)]
        title: String,
        /// PR body (summary)
        #[arg(long, default_value = "Generated by Plan Executor Agent")]
        body: String,
    },
}

#[derive(Subcommand)]
enum ModelAction {
    /// Show current LLM configuration
    Show,
    /// List available providers and their default models
    List,
    /// Set provider and optionally model (e.g., "anthropic/claude-sonnet-4")
    Set {
        /// Provider name, optionally with /model suffix
        target: Option<String>,
    },
}

#[derive(Subcommand)]
enum SessionAction {
    /// List all plans
    List {
        /// Maximum plans to show (default: 10)
        #[arg(long, default_value_t = 10)]
        limit: usize,
    },
    /// Show plan details and steps
    Show {
        /// Plan ID
        id: String,
    },
    /// Resume execution of a plan
    Resume {
        /// Plan ID
        id: String,
        /// Database path for the plan
        #[arg(long, default_value = "agent.db")]
        db: String,
        /// Optional input for WaitForInput steps
        #[arg(long)]
        input: Option<String>,
    },
    /// Delete a plan and its checkpoints
    Delete {
        /// Plan ID
        id: String,
    },
    /// Delete completed/failed plans older than N days
    Prune {
        /// Age in days (default: 30)
        #[arg(long, default_value_t = 30)]
        days: u64,
    },
}

#[derive(Subcommand)]
enum Commands {
    /// Run a single plan by ID
    Run {
        /// Plan ID to execute
        #[arg(long)]
        task: String,
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
        /// Input to provide if the plan is waiting for user input
        #[arg(long)]
        input: Option<String>,
    },
    /// Run the built-in demo plan
    Demo {
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
    /// Manage skills
    Skills {
        #[command(subcommand)]
        action: SkillAction,
    },
    /// Git integration: status, commit, PR
    Git {
        #[command(subcommand)]
        action: GitAction,
    },
    /// Manage configuration (API keys, model settings)
    Config {
        #[command(subcommand)]
        action: ConfigAction,
    },
    /// Launch the desktop GUI
    #[cfg(feature = "gui")]
    Gui {
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
    /// Start MCP protocol server over stdio
    McpServer,
    /// Show system status overview
    Status {
        /// Short one-line output (for scripts)
        #[arg(long)]
        short: bool,
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
    /// Show/switch LLM provider and model
    Model {
        #[command(subcommand)]
        action: Option<ModelAction>,
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
    /// List, show, resume, delete plans
    Session {
        #[command(subcommand)]
        action: SessionAction,
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
    /// Diagnose configuration and environment
    Doctor {
        /// Attempt to auto-fix warnings
        #[arg(long)]
        fix: bool,
    },
    /// View and follow agent logs
    Logs {
        /// Follow log file in real-time
        #[arg(long)]
        follow: bool,
        /// Number of lines to show (default: 50)
        #[arg(long, default_value_t = 50)]
        lines: usize,
        /// Filter by log level (e.g., WARN, ERROR)
        #[arg(long)]
        level: Option<String>,
        /// Show previous session log instead
        #[arg(long)]
        prev: bool,
    },
    /// Start in server mode (placeholder for future daemon)
    Serve {
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
        /// Port to listen on
        #[arg(long, default_value_t = 8080)]
        port: u16,
    },
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();
    tracing_setup::init_logging(cli.verbose);

    match cli.command {
        None => {
            // Build the agent engine, then launch the three-panel TUI
            let data_dir = tracing_setup::data_dir();
            std::fs::create_dir_all(&data_dir).ok();
            let db_path = data_dir.join("agent.db");
            let (repo, agent, tool_executor) = build_engine(db_path.to_str().unwrap_or("agent.db")).await?;

            // Capture tokio handle on the main async thread (not inside spawn_blocking)
            let handle = tokio::runtime::Handle::current();

            let err_msg = tokio::task::spawn_blocking(move || {
                crate::cli::run_tui_with_agent(repo, agent, tool_executor, handle)
            })
            .await
            .map_err(|e| anyhow::anyhow!("TUI task failed: {e}"))?;

            if let Err(e) = err_msg {
                // Make sure stderr is flushed so user sees the panic message
                use std::io::Write;
                let _ = writeln!(std::io::stderr(), "\nrupoo error: {}", e);
                anyhow::bail!("TUI error: {}", e);
            }
        }
        Some(cmd) => run_cmd(cmd).await?,
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// CLI command dispatcher
// ---------------------------------------------------------------------------

async fn run_cmd(cmd: Commands) -> anyhow::Result<()> {
    match cmd {
        Commands::Run { task, db, input } => {
            let db = resolve_db(db);
            let (repo, agent, _tool_executor) = build_engine(&db).await?;
            execute_plan(&repo, &agent, &task, input.as_deref()).await?;
        }
        #[cfg(feature = "gui")]
        Commands::Gui { db } => {
            let db = resolve_db(db);
            launch_gui(&db)?;
        }
        Commands::Git { action } => match action {
            GitAction::Status => {
                let repo = rupoo::git::GitRepo::open(".")?;
                let branch = repo.current_branch()?;
                let statuses = repo.status()?;
                println!("Branch: {branch}");
                println!("Status ({} files):", statuses.len());
                for s in &statuses {
                    println!("  [{:>15}] {}", s.status, s.path);
                }
            }
            GitAction::Commit { message, task } => {
                let repo = rupoo::git::GitRepo::open(".")?;
                let hash = if let Some(task_id) = task {
                    repo.commit_with_task_ref(&message, &task_id)?
                } else {
                    repo.commit_all(&message)?
                };
                println!("Committed {hash}: {message}");
            }
            GitAction::Pr { title, body } => {
                let url = rupoo::git::create_gh_pr(&title, &body)?;
                println!("PR created: {url}");
            }
        },
        Commands::Config { action } => match action {
            ConfigAction::Set { key, value } => {
                let (repo, _agent, _tool_executor) = build_engine("agent.db").await?;
                repo.set_setting(&key, &value).await?;
                info!(key = %key, "configuration saved");
                println!("Set {key} = {value}");
            }
            ConfigAction::Get { key } => {
                let (repo, _agent, _tool_executor) = build_engine("agent.db").await?;
                match repo.get_setting(&key).await? {
                    Some(value) => println!("{key} = {value}"),
                    None => println!("{key} is not set"),
                }
            }
            ConfigAction::List => {
                let (repo, _agent, _tool_executor) = build_engine("agent.db").await?;
                let settings = repo.list_settings().await?;
                if settings.is_empty() {
                    println!("No configuration set.");
                } else {
                    for (k, v) in &settings {
                        let display = if k.starts_with("api_key") {
                            format!("{}...", &v[..v.len().min(8)])
                        } else {
                            v.clone()
                        };
                        println!("  {k} = {display}");
                    }
                }
            }
        },
        Commands::Skills { action } => match action {
            SkillAction::List => {
                let manager = SkillManager::new(SkillManager::default_dir());
                let skills = manager.list_skills()?;
                println!("Available skills ({})", skills.len());
                for s in &skills {
                    let skill = manager.load_skill(s)?;
                    println!("  {:<20} {}", skill.name, skill.description);
                }
            }
            SkillAction::Show { name } => {
                let manager = SkillManager::new(SkillManager::default_dir());
                let skill = manager.load_skill(&name)?;
                println!("Name:        {}", skill.name);
                println!("Description: {}", skill.description);
                println!("Version:     {}", skill.version);
                println!("Triggers:    {:?}", skill.trigger);
                println!("Steps:");
                for (i, step) in skill.steps.iter().enumerate() {
                    println!("  [{i}] {step:?}");
                }
            }
            SkillAction::Run { name, db } => {
                let db = resolve_db(db);
                let manager = SkillManager::new(SkillManager::default_dir());
                let skill = manager.load_skill(&name)?;
                let plan = manager.skill_to_plan(&skill);
                let (repo, agent, _tool_executor) = build_engine(&db).await?;
                repo.save_plan(&plan).await?;
                info!(plan_id = %plan.id, skill = %name, "skill plan saved");
                print_plan_summary(&plan);
                execute_plan(&repo, &agent, &plan.id, None).await?;
            }
            SkillAction::InstallBuiltin => {
                SkillManager::install_builtin_skills()?;
                println!("Built-in skills installed successfully.");
            }
            SkillAction::Learn {
                plan_id,
                name,
                description,
                db,
            } => {
                let db = resolve_db(db);
                let repo = Arc::new(TaskRepo::new(&db)?);
                let plan = repo.load_plan(&plan_id).await?;
                let skill =
                    SkillManager::plan_to_skill(&plan, &name, &description);
                let manager = SkillManager::new(SkillManager::default_dir());
                manager.save_skill(&skill)?;
                println!(
                    "Learned skill '{}' from plan '{}' ({} steps)",
                    name,
                    plan.name,
                    skill.steps.len()
                );
            }
        },
        Commands::Demo { db } => {
            let db = resolve_db(db);
            let (repo, agent, _tool_executor) = build_engine(&db).await?;

            let plan = Plan::new(
                "Demo Plan",
                vec![
                    think_step("Analyze the current project structure"),
                    tool_call_step(
                        "list_directory",
                        serde_json::json!({"path": "."}),
                    ),
                    think_step("Evaluate the directory listing results"),
                    wait_for_input_step("Do you want to continue with file reading?"),
                    tool_call_step(
                        "file_read",
                        serde_json::json!({"path": "Cargo.toml"}),
                    ),
                    think_step("Summarize findings from the Cargo.toml"),
                    tool_call_step(
                        "echo",
                        serde_json::json!({"message": "All steps completed successfully!"}),
                    ),
                    finish_step("Demo plan execution finished"),
                ],
            );

            repo.save_plan(&plan).await?;
            info!(plan_id = %plan.id, name = %plan.name, "demo plan saved");

            print_plan_summary(&plan);
            execute_plan(&repo, &agent, &plan.id, None).await?;
        }
        Commands::McpServer => {
            rupoo::mcp_server::run_mcp_server().await?;
        }
        Commands::Serve { db: _, port } => {
            println!("  {} Server mode (port {port}) — development only. Not for production use.", console::style("⚠").yellow());
            println!("  {} Must bind to 127.0.0.1 and add auth before exposing.", console::style("→").dim());
            #[cfg(feature = "gui")]
            {
                info!("system tray enabled");
                rupoo::tray::run_service();
            }
            #[cfg(not(feature = "gui"))]
            {
                info!("compile with --features gui for system tray support");
                tokio::signal::ctrl_c().await?;
            }
        }
        Commands::Status { short, db } => {
            let db = resolve_db(db);
            crate::cli::cmds::status::run(&db, short).await?;
        }
        Commands::Model { action, db } => {
            let db = resolve_db(db);
            crate::cli::cmds::model::run(&db, action).await?;
        }
        Commands::Session { action, db } => {
            let db = resolve_db(db);
            crate::cli::cmds::session::run(&db, action).await?;
        }
        Commands::Doctor { fix } => {
            crate::cli::cmds::doctor::run(fix).await?;
        }
        Commands::Logs { follow, lines, level, prev } => {
            crate::cli::cmds::logs::run(follow, lines, level.as_deref(), prev).await?;
        }
    }

    Ok(())
}

/// Resolve database path, defaulting to ~/.rupoo/agent.db.
fn resolve_db(db: Option<String>) -> String {
    db.unwrap_or_else(|| {
        tracing_setup::data_dir()
            .join("agent.db")
            .to_string_lossy()
            .to_string()
    })
}

// ---------------------------------------------------------------------------
// Engine builders
// ---------------------------------------------------------------------------

async fn build_engine(db_path: &str) -> anyhow::Result<(
    Arc<TaskRepo>,
    Agent,
    std::sync::Arc<Box<dyn rupoo::agent::ToolExecutor>>,
)> {
    let repo = Arc::new(TaskRepo::new(db_path)?);

    // Load safety configuration from file if present
    let safety_ctx = {
        let config_path = std::path::Path::new("rupoo-config.toml");
        if config_path.exists() {
            SafetyContext::from_config(config_path)
        } else {
            SafetyContext::default()
        }
    };

    // Both the Agent and the Arc-wrapped ToolExecutor share the same SafetyContext.
    // The Arc copy is used by AgentUiBridge for direct approval-time tool execution.
    let tool_executor: Box<dyn rupoo::agent::ToolExecutor> =
        Box::new(McpToolExecutor::with_safety(safety_ctx.clone()));
    let tool_executor_arc: std::sync::Arc<Box<dyn rupoo::agent::ToolExecutor>> =
        std::sync::Arc::new(Box::new(McpToolExecutor::with_safety(safety_ctx.clone())));

    let jail_root = safety_ctx.jail_root().map(|p| p.to_path_buf());
    let mut agent = Agent::new(Arc::clone(&repo), tool_executor);
    agent.safety_ctx = safety_ctx;

    if let Some(api_key) = repo.get_setting("api_key.anthropic").await? {
        let mut cfg = rupoo::llm::LlmConfig::new(
            rupoo::llm::LlmProvider::Anthropic,
            Some(api_key),
        );
        if let Some(model) = repo.get_setting("model.anthropic").await? {
            cfg.model = model;
        }
        let gateway = if let Some(ref root) = jail_root {
            rupoo::llm::LlmGateway::with_jail(cfg, root.clone())
        } else {
            rupoo::llm::LlmGateway::new(cfg)
        };
        agent = agent.with_llm(gateway);
        info!("Anthropic LLM configured");
    } else if let Some(api_key) = repo.get_setting("api_key.openai").await? {
        let mut cfg = rupoo::llm::LlmConfig::new(
            rupoo::llm::LlmProvider::OpenAI,
            Some(api_key),
        );
        if let Some(model) = repo.get_setting("model.openai").await? {
            cfg.model = model;
        }
        if let Some(base_url) = repo.get_setting("base_url.openai").await? {
            cfg.base_url = Some(base_url);
        }
        let gateway = if let Some(ref root) = jail_root {
            rupoo::llm::LlmGateway::with_jail(cfg, root.clone())
        } else {
            rupoo::llm::LlmGateway::new(cfg)
        };
        agent = agent.with_llm(gateway);
        info!("OpenAI-compatible LLM configured");
    } else {
        info!("no LLM configured, using dummy think output");
    }

    Ok((repo, agent, tool_executor_arc))
}

async fn execute_plan(
    _repo: &Arc<TaskRepo>,
    agent: &Agent,
    plan_id: &str,
    input: Option<&str>,
) -> anyhow::Result<()> {
    info!(plan_id = %plan_id, "starting/resuming plan");

    let mut plan = match agent.resume(plan_id).await? {
        Some(p) => p,
        None => {
            info!("plan already completed, nothing to do");
            return Ok(());
        }
    };

    info!(
        plan_id = %plan_id,
        status = ?plan.status,
        current_step = plan.current_step_index,
        total_steps = plan.steps.len(),
        "plan loaded"
    );

    loop {
        let step_index = plan.current_step_index;

        if let Some(input_val) = input {
            let is_waiting = plan.steps.get(step_index).is_some_and(|s| s.is_waiting());
            if is_waiting {
                info!(plan_id = %plan_id, step = step_index, input = %input_val, "injecting input into WaitForInput step");
                let outcome = agent.inject_input(&mut plan, step_index, input_val).await?;
                match outcome {
                    rupoo::agent::StepOutcome::Advanced => {
                        info!(plan_id = %plan_id, step = step_index, "input injected, step completed");
                        continue;
                    }
                    _ => {
                        anyhow::bail!("unexpected outcome from inject_input: {:?}", outcome);
                    }
                }
            }
        }

        let outcome = agent.run_next_step(&mut plan).await?;

        match outcome {
            rupoo::agent::StepOutcome::Advanced => {
                info!(
                    plan_id = %plan_id,
                    step = step_index,
                    "step completed"
                );
            }
            rupoo::agent::StepOutcome::Finished => {
                info!(plan_id = %plan_id, "plan execution finished");
                print_plan_result(&plan);
                break;
            }
            rupoo::agent::StepOutcome::WaitingForInput(prompt) => {
                println!("\n=== WAITING FOR INPUT ===");
                println!("Prompt: {prompt}");
                println!("==========================");
                if input.is_some() {
                    println!("Input was provided but the step type was not WaitForInput at resume time.");
                } else {
                    println!("The plan is paused. Re-run with `--input <text>` to provide input.");
                }
                break;
            }
            rupoo::agent::StepOutcome::Failed(err) => {
                println!("\n=== PLAN FAILED ===");
                println!("Error: {err}");
                println!("====================\n");
                break;
            }
            rupoo::agent::StepOutcome::RequiresApproval { .. } => {
                println!("\n=== REQUIRES APPROVAL (TUI only) ===");
                println!("This plan has a tool that requires TUI approval.");
                println!("Run it with the interactive TUI (rupoo without --run flag) instead.");
                break;
            }
        }
    }

    Ok(())
}

fn print_plan_summary(plan: &Plan) {
    println!("\n=== PLAN: {} ===", plan.name);
    println!("ID: {}", plan.id);
    println!("Steps:");
    for (i, step) in plan.steps.iter().enumerate() {
        let label = match step {
            rupoo::task::Step::Think { instruction, .. } => format!("THINK: {instruction}"),
            rupoo::task::Step::ToolCall { tool_name, params, .. } => {
                format!("TOOL: {tool_name} ({})", params)
            }
            rupoo::task::Step::WaitForInput { prompt, .. } => format!("WAIT: {prompt}"),
            rupoo::task::Step::Finish { summary, .. } => format!("FINISH: {summary}"),
            rupoo::task::Step::Exec { command, .. } => format!("EXEC: {command}"),
            rupoo::task::Step::HttpRequest { url, method, .. } => format!("HTTP: {method:?} {url}"),
            rupoo::task::Step::BrowserAction { action, .. } => format!("BROWSER: {action:?}"),
        };
        println!("  [{i}] {label}");
    }
    println!("==========================\n");
}

fn print_plan_result(plan: &Plan) {
    println!("\n=== PLAN RESULT ===");
    println!("Name: {}", plan.name);
    println!("Status: {:?}", plan.status);
    for (i, step) in plan.steps.iter().enumerate() {
        let status_mark = match step.status() {
            rupoo::task::StepStatus::Completed => "✓",
            rupoo::task::StepStatus::Failed => "✗",
            rupoo::task::StepStatus::Running => "▶",
            rupoo::task::StepStatus::Pending => "·",
            rupoo::task::StepStatus::WaitingForInput => "⊘",
        };

        let label = match step {
            rupoo::task::Step::Think { instruction, output, .. } => {
                format!("THINK: {instruction} | out: {}", output.as_deref().unwrap_or("-"))
            }
            rupoo::task::Step::ToolCall { tool_name, result, .. } => {
                let r = result
                    .as_ref()
                    .map(|v| v.to_string())
                    .unwrap_or_else(|| "-".to_string());
                format!("TOOL: {tool_name} | result: {r}")
            }
            rupoo::task::Step::WaitForInput { prompt, response, .. } => {
                format!("WAIT: {prompt} | response: {}", response.as_deref().unwrap_or("(pending)"))
            }
            rupoo::task::Step::Finish { summary, .. } => format!("FINISH: {summary}"),
            rupoo::task::Step::Exec { command, output, .. } => {
                format!("EXEC: {command} | out: {}", output.as_deref().unwrap_or("-"))
            }
            rupoo::task::Step::HttpRequest { url, response, .. } => {
                format!("HTTP: {url} | resp: {}", response.as_deref().unwrap_or("-"))
            }
            rupoo::task::Step::BrowserAction { action, output, .. } => {
                format!("BROWSER: {action:?} | out: {}", output.as_deref().unwrap_or("-"))
            }
        };
        println!("  {status_mark} [{i}] {label}");
    }
    println!("========================\n");
}

#[cfg(feature = "gui")]
fn launch_gui(db_path: &str) -> anyhow::Result<()> {
    let state = rupoo::gui::AppState::new(db_path)?;
    let handle = tokio::runtime::Handle::current();
    let app = rupoo::gui::GuiApp::new(state, Some(handle));
    let native_options = eframe::NativeOptions::default();
    eframe::run_native(
        "Yupoo",
        native_options,
        Box::new(move |_cc| Box::new(app)),
    )
    .map_err(|e| anyhow::anyhow!("GUI error: {e}"))
}
