//! CLI subcommand dispatch — extracted from main.rs for maintainability.

use std::sync::Arc;
use tracing::info;

use rupoo::db::TaskRepo;
use rupoo::skill::SkillManager;
use rupoo::task::{finish_step, think_step, tool_call_step, wait_for_input_step, Plan};

// ---------------------------------------------------------------------------
// Enum definitions (moved from main.rs)
// ---------------------------------------------------------------------------

#[derive(clap::Subcommand)]
pub enum SkillAction {
    /// List available skills
    List,
    /// Show details of a specific skill
    Show {
        /// Skill name
        name: String,
    },
    /// Run a skill (convert to plan and execute)
    Run {
        /// Skill name
        name: String,
        /// Database path
        #[arg(long)]
        db: Option<String>,
    },
    /// Install the built-in skills
    InstallBuiltin,
    /// Learn a skill from a completed plan
    Learn {
        /// Plan ID to learn from
        plan_id: String,
        /// Name for the new skill
        name: String,
        /// Description (optional)
        #[arg(long, default_value = "Learned from completed plan")]
        description: String,
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
}

#[derive(clap::Subcommand)]
pub enum ConfigAction {
    /// Set a configuration value (e.g., set api_key.anthropic sk-ant-xxx)
    Set {
        /// Configuration key (e.g. "api_key.anthropic", "model.ollama.base_url")
        key: String,
        /// Value to set
        value: String,
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
    /// Get a configuration value
    Get {
        key: String,
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
    /// List all configuration values
    List {
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
}

#[derive(clap::Subcommand)]
pub enum GitAction {
    /// Show git status
    Status,
    /// Stage all changes and commit
    Commit {
        /// Commit message
        #[arg(long)]
        message: String,
        /// Optional task ID to reference
        #[arg(long)]
        task: Option<String>,
    },
    /// Create a GitHub PR
    Pr {
        /// PR title
        #[arg(long)]
        title: String,
        /// PR body (summary)
        #[arg(long, default_value = "Generated by Plan Executor Agent")]
        body: String,
    },
}

#[derive(clap::Subcommand)]
pub enum ModelAction {
    /// Show current LLM configuration
    Show,
    /// List available providers and their default models
    List,
    /// Set provider and optionally model (e.g., "anthropic/claude-sonnet-4")
    Set {
        /// Provider name, optionally with /model suffix
        target: Option<String>,
    },
}

#[derive(clap::Subcommand)]
pub enum SessionAction {
    /// List all plans
    List {
        /// Maximum plans to show (default: 10)
        #[arg(long, default_value_t = 10)]
        limit: usize,
    },
    /// Show plan details and steps
    Show {
        /// Plan ID
        id: String,
    },
    /// Resume execution of a plan
    Resume {
        /// Plan ID
        id: String,
        /// Database path for the plan
        #[arg(long, default_value = "agent.db")]
        db: String,
        /// Optional input for WaitForInput steps
        #[arg(long)]
        input: Option<String>,
    },
    /// Delete a plan and its checkpoints
    Delete {
        /// Plan ID
        id: String,
    },
    /// Delete completed/failed plans older than N days
    Prune {
        /// Age in days (default: 30)
        #[arg(long, default_value_t = 30)]
        days: u64,
    },
}

// ---------------------------------------------------------------------------
// CLI command dispatcher
// ---------------------------------------------------------------------------

pub async fn run_cmd(cmd: super::Commands) -> anyhow::Result<()> {
    match cmd {
        super::Commands::Run { task, db, input } => {
            let db = resolve_db(db);
            let (repo, agent, _tool_executor, _llm_router) = crate::build_engine::build_engine(&db).await?;
            crate::executor::execute_plan(&repo, &agent, &task, input.as_deref()).await?;
        }
        super::Commands::Git { action } => {
            match action {
                GitAction::Status => {
                    let repo = rupoo::git::GitRepo::open(".")?;
                    let branch = repo.current_branch()?;
                    let statuses = repo.status()?;
                    println!("Branch: {branch}");
                    println!("Status ({} files):", statuses.len());
                    for s in &statuses {
                        println!("  [{:>15}] {}", s.status, s.path);
                    }
                }
                GitAction::Commit { message, task } => {
                    let repo = rupoo::git::GitRepo::open(".")?;
                    let hash = if let Some(task_id) = task {
                        repo.commit_with_task_ref(&message, &task_id)?
                    } else {
                        repo.commit_all(&message)?
                    };
                    println!("Committed {hash}: {message}");
                }
                GitAction::Pr { title, body } => {
                    let url = rupoo::git::create_gh_pr(&title, &body)?;
                    println!("PR created: {url}");
                }
            }
        }
        super::Commands::Config { action } => match action {
            ConfigAction::Set { key, value, db } => {
                let db = resolve_db(db);
                let (repo, _agent, _tool_executor, _llm_router) = crate::build_engine::build_engine(&db).await?;
                repo.set_setting(&key, &value).await?;
                info!(key = %key, "configuration saved");
                println!("Set {key} = {value}");
            }
            ConfigAction::Get { key, db } => {
                let db = resolve_db(db);
                let (repo, _agent, _tool_executor, _llm_router) = crate::build_engine::build_engine(&db).await?;
                match repo.get_setting(&key).await? {
                    Some(value) => println!("{key} = {value}"),
                    None => println!("{key} is not set"),
                }
            }
            ConfigAction::List { db } => {
                let db = resolve_db(db);
                let (repo, _agent, _tool_executor, _llm_router) = crate::build_engine::build_engine(&db).await?;
                let settings = repo.list_settings().await?;
                if settings.is_empty() {
                    println!("No configuration set.");
                } else {
                    for (k, v) in &settings {
                        let display = if k.starts_with("api_key") {
                            format!("{}...", &v[..v.len().min(8)])
                        } else {
                            v.clone()
                        };
                        println!("  {k} = {display}");
                    }
                }
            }
        },
        super::Commands::Skills { action } => match action {
            SkillAction::List => {
                let manager = SkillManager::new(SkillManager::default_dir());
                let skills = manager.list_skills()?;
                println!("Available skills ({})", skills.len());
                for s in &skills {
                    let skill = manager.load_skill(s)?;
                    println!("  {:<20} {}", skill.name, skill.description);
                }
            }
            SkillAction::Show { name } => {
                let manager = SkillManager::new(SkillManager::default_dir());
                let skill = manager.load_skill(&name)?;
                println!("Name:        {}", skill.name);
                println!("Description: {}", skill.description);
                println!("Version:     {}", skill.version);
                println!("Triggers:    {:?}", skill.trigger);
                println!("Steps:");
                for (i, step) in skill.steps.iter().enumerate() {
                    println!("  [{i}] {step:?}");
                }
            }
            SkillAction::Run { name, db } => {
                let db = resolve_db(db);
                let manager = SkillManager::new(SkillManager::default_dir());
                let skill = manager.load_skill(&name)?;
                let plan = manager.skill_to_plan(&skill);
                let (repo, agent, _tool_executor, _llm_router) = crate::build_engine::build_engine(&db).await?;
                repo.save_plan(&plan).await?;
                info!(plan_id = %plan.id, skill = %name, "skill plan saved");
                print_plan_summary(&plan);
                crate::executor::execute_plan(&repo, &agent, &plan.id, None).await?;
            }
            SkillAction::InstallBuiltin => {
                SkillManager::install_builtin_skills()?;
                println!("Built-in skills installed successfully.");
            }
            SkillAction::Learn {
                plan_id,
                name,
                description,
                db,
            } => {
                let db = resolve_db(db);
                let repo = Arc::new(TaskRepo::new(&db)?);
                let plan = repo.load_plan(&plan_id).await?;
                let skill =
                    SkillManager::plan_to_skill(&plan, &name, &description);
                let manager = SkillManager::new(SkillManager::default_dir());
                manager.save_skill(&skill)?;
                println!(
                    "Learned skill '{}' from plan '{}' ({} steps)",
                    name,
                    plan.name,
                    skill.steps.len()
                );
            }
        },
        super::Commands::Demo { db } => {
            let db = resolve_db(db);
            let (repo, agent, _tool_executor, _llm_router) = crate::build_engine::build_engine(&db).await?;

            let plan = Plan::new(
                "Demo Plan",
                vec![
                    think_step("Analyze the current project structure"),
                    tool_call_step(
                        "list_directory",
                        serde_json::json!({"path": "."}),
                    ),
                    think_step("Evaluate the directory listing results"),
                    wait_for_input_step("Do you want to continue with file reading?"),
                    tool_call_step(
                        "file_read",
                        serde_json::json!({"path": "Cargo.toml"}),
                    ),
                    think_step("Summarize findings from the Cargo.toml"),
                    tool_call_step(
                        "echo",
                        serde_json::json!({"message": "All steps completed successfully!"}),
                    ),
                    finish_step("Demo plan execution finished"),
                ],
            );

            repo.save_plan(&plan).await?;
            info!(plan_id = %plan.id, name = %plan.name, "demo plan saved");

            print_plan_summary(&plan);
            crate::executor::execute_plan(&repo, &agent, &plan.id, None).await?;
        }
        super::Commands::McpServer => {
            rupoo::mcp_server::run_mcp_server().await?;
        }
        super::Commands::Serve { db: _, port } => {
            println!("  {} Server mode (port {port}) — development only. Not for production use.", console::style("⚠").yellow());
            println!("  {} Must bind to 127.0.0.1 and add auth before exposing.", console::style("→").dim());
            tokio::signal::ctrl_c().await?;
        }
        super::Commands::Status { short, db } => {
            let db = resolve_db(db);
            crate::cli::cmds::status::run(&db, short).await?;
        }
        super::Commands::Model { action, db } => {
            let db = resolve_db(db);
            crate::cli::cmds::model::run(&db, action).await?;
        }
        super::Commands::Session { action, db } => {
            let db = resolve_db(db);
            crate::cli::cmds::session::run(&db, action).await?;
        }
        super::Commands::Doctor { fix } => {
            crate::cli::cmds::doctor::run(fix).await?;
        }
        super::Commands::Logs { follow, lines, level, prev } => {
            crate::cli::cmds::logs::run(follow, lines, level.as_deref(), prev).await?;
        }
    }

    Ok(())
}

/// Resolve database path, defaulting to ~/.rupoo/agent.db.
fn resolve_db(db: Option<String>) -> String {
    db.unwrap_or_else(|| {
        crate::tracing_setup::data_dir()
            .join("agent.db")
            .to_string_lossy()
            .to_string()
    })
}

fn print_plan_summary(plan: &Plan) {
    println!("\n=== PLAN: {} ===", plan.name);
    println!("ID: {}", plan.id);
    println!("Steps:");
    for (i, step) in plan.steps.iter().enumerate() {
        let label = match step {
            rupoo::task::Step::Think { instruction, .. } => format!("THINK: {instruction}"),
            rupoo::task::Step::ToolCall { tool_name, params, .. } => {
                format!("TOOL: {tool_name} ({})", params)
            }
            rupoo::task::Step::WaitForInput { prompt, .. } => format!("WAIT: {prompt}"),
            rupoo::task::Step::Finish { summary, .. } => format!("FINISH: {summary}"),
            rupoo::task::Step::Exec { command, .. } => format!("EXEC: {command}"),
            rupoo::task::Step::HttpRequest { url, method, .. } => format!("HTTP: {method:?} {url}"),
            rupoo::task::Step::BrowserAction { action, .. } => format!("BROWSER: {action:?}"),
        };
        println!("  [{i}] {label}");
    }
    println!("==========================\n");
}
