use std::sync::Arc;

use clap::{Parser, Subcommand};
use tracing::info;

use rupoo::agent::Agent;
use rupoo::db::TaskRepo;
use rupoo::mcp::McpToolExecutor;
use rupoo::skill::SkillManager;
use rupoo::task::{finish_step, think_step, tool_call_step, wait_for_input_step, Plan};

mod cli;
mod tracing_setup;

/// Rupoo — AI-powered assistant for your terminal.
/// Run without subcommands to enter interactive mode.
#[derive(Parser)]
#[command(name = "rupoo", version = "0.2.0", about)]
struct Cli {
    /// Show debug-level logs on stderr.
    #[arg(long, global = true)]
    verbose: bool,

    /// Optional subcommand. If omitted, enters interactive TUI.
    #[command(subcommand)]
    command: Option<Commands>,
}

#[derive(Subcommand)]
enum SkillAction {
    /// List available skills
    List,
    /// Show details of a specific skill
    Show {
        /// Skill name
        name: String,
    },
    /// Run a skill (convert to plan and execute)
    Run {
        /// Skill name
        name: String,
        /// Database path
        #[arg(long)]
        db: Option<String>,
    },
    /// Install the built-in skills
    InstallBuiltin,
    /// Learn a skill from a completed plan
    Learn {
        /// Plan ID to learn from
        plan_id: String,
        /// Name for the new skill
        name: String,
        /// Description (optional)
        #[arg(long, default_value = "Learned from completed plan")]
        description: String,
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
}

#[derive(Subcommand)]
enum ConfigAction {
    /// Set a configuration value (e.g., set api_key.anthropic sk-ant-xxx)
    Set {
        /// Configuration key (e.g. "api_key.anthropic", "model.ollama.base_url")
        key: String,
        /// Value to set
        value: String,
    },
    /// Get a configuration value
    Get {
        key: String,
    },
    /// List all configuration values
    List,
}

#[derive(Subcommand)]
enum GitAction {
    /// Show git status
    Status,
    /// Stage all changes and commit
    Commit {
        /// Commit message
        #[arg(long)]
        message: String,
        /// Optional task ID to reference
        #[arg(long)]
        task: Option<String>,
    },
    /// Create a GitHub PR
    Pr {
        /// PR title
        #[arg(long)]
        title: String,
        /// PR body (summary)
        #[arg(long, default_value = "Generated by Plan Executor Agent")]
        body: String,
    },
}

#[derive(Subcommand)]
enum ModelAction {
    /// Show current LLM configuration
    Show,
    /// List available providers and their default models
    List,
    /// Set provider and optionally model (e.g., "anthropic/claude-sonnet-4")
    Set {
        /// Provider name, optionally with /model suffix
        target: Option<String>,
    },
}

#[derive(Subcommand)]
enum SessionAction {
    /// List all plans
    List {
        /// Maximum plans to show (default: 10)
        #[arg(long, default_value_t = 10)]
        limit: usize,
    },
    /// Show plan details and steps
    Show {
        /// Plan ID
        id: String,
    },
    /// Resume execution of a plan
    Resume {
        /// Plan ID
        id: String,
        /// Database path for the plan
        #[arg(long, default_value = "agent.db")]
        db: String,
        /// Optional input for WaitForInput steps
        #[arg(long)]
        input: Option<String>,
    },
    /// Delete a plan and its checkpoints
    Delete {
        /// Plan ID
        id: String,
    },
    /// Delete completed/failed plans older than N days
    Prune {
        /// Age in days (default: 30)
        #[arg(long, default_value_t = 30)]
        days: u64,
    },
}

#[derive(Subcommand)]
enum Commands {
    /// Run a single plan by ID
    Run {
        /// Plan ID to execute
        #[arg(long)]
        task: String,
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
        /// Input to provide if the plan is waiting for user input
        #[arg(long)]
        input: Option<String>,
    },
    /// Run the built-in demo plan
    Demo {
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
    /// Manage skills
    Skills {
        #[command(subcommand)]
        action: SkillAction,
    },
    /// Git integration: status, commit, PR
    Git {
        #[command(subcommand)]
        action: GitAction,
    },
    /// Manage configuration (API keys, model settings)
    Config {
        #[command(subcommand)]
        action: ConfigAction,
    },
    /// Launch the desktop GUI
    #[cfg(feature = "gui")]
    Gui {
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
    /// Start MCP protocol server over stdio
    McpServer,
    /// Show system status overview
    Status {
        /// Short one-line output (for scripts)
        #[arg(long)]
        short: bool,
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
    /// Show/switch LLM provider and model
    Model {
        #[command(subcommand)]
        action: Option<ModelAction>,
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
    /// List, show, resume, delete plans
    Session {
        #[command(subcommand)]
        action: SessionAction,
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
    },
    /// Diagnose configuration and environment
    Doctor {
        /// Attempt to auto-fix warnings
        #[arg(long)]
        fix: bool,
    },
    /// View and follow agent logs
    Logs {
        /// Follow log file in real-time
        #[arg(long)]
        follow: bool,
        /// Number of lines to show (default: 50)
        #[arg(long, default_value_t = 50)]
        lines: usize,
        /// Filter by log level (e.g., WARN, ERROR)
        #[arg(long)]
        level: Option<String>,
        /// Show previous session log instead
        #[arg(long)]
        prev: bool,
    },
    /// Start in server mode (placeholder for future daemon)
    Serve {
        /// Database path (default: ~/.rupoo/agent.db)
        #[arg(long)]
        db: Option<String>,
        /// Port to listen on
        #[arg(long, default_value_t = 8080)]
        port: u16,
    },
}

// ---------------------------------------------------------------------------
// Shared state between REPL and async event loop
// ---------------------------------------------------------------------------

struct ReplState {
    repo: Arc<TaskRepo>,
    agent: Agent,
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();
    tracing_setup::init_logging(cli.verbose);

    match cli.command {
        None => run_repl().await?,
        Some(cmd) => run_cmd(cmd).await?,
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// CLI command dispatcher
// ---------------------------------------------------------------------------

async fn run_cmd(cmd: Commands) -> anyhow::Result<()> {
    match cmd {
        Commands::Run { task, db, input } => {
            let db = resolve_db(db);
            let (repo, agent) = build_engine(&db).await?;
            execute_plan(&repo, &agent, &task, input.as_deref()).await?;
        }
        #[cfg(feature = "gui")]
        Commands::Gui { db } => {
            let db = resolve_db(db);
            launch_gui(&db)?;
        }
        Commands::Git { action } => match action {
            GitAction::Status => {
                let repo = rupoo::git::GitRepo::open(".")?;
                let branch = repo.current_branch()?;
                let statuses = repo.status()?;
                println!("Branch: {branch}");
                println!("Status ({} files):", statuses.len());
                for s in &statuses {
                    println!("  [{:>15}] {}", s.status, s.path);
                }
            }
            GitAction::Commit { message, task } => {
                let repo = rupoo::git::GitRepo::open(".")?;
                let hash = if let Some(task_id) = task {
                    repo.commit_with_task_ref(&message, &task_id)?
                } else {
                    repo.commit_all(&message)?
                };
                println!("Committed {hash}: {message}");
            }
            GitAction::Pr { title, body } => {
                let url = rupoo::git::create_gh_pr(&title, &body)?;
                println!("PR created: {url}");
            }
        },
        Commands::Config { action } => match action {
            ConfigAction::Set { key, value } => {
                let (repo, _agent) = build_engine("agent.db").await?;
                repo.set_setting(&key, &value).await?;
                info!(key = %key, "configuration saved");
                println!("Set {key} = {value}");
            }
            ConfigAction::Get { key } => {
                let (repo, _agent) = build_engine("agent.db").await?;
                match repo.get_setting(&key).await? {
                    Some(value) => println!("{key} = {value}"),
                    None => println!("{key} is not set"),
                }
            }
            ConfigAction::List => {
                let (repo, _agent) = build_engine("agent.db").await?;
                let settings = repo.list_settings().await?;
                if settings.is_empty() {
                    println!("No configuration set.");
                } else {
                    for (k, v) in &settings {
                        let display = if k.starts_with("api_key") {
                            format!("{}...", &v[..v.len().min(8)])
                        } else {
                            v.clone()
                        };
                        println!("  {k} = {display}");
                    }
                }
            }
        },
        Commands::Skills { action } => match action {
            SkillAction::List => {
                let manager = SkillManager::new(SkillManager::default_dir());
                let skills = manager.list_skills()?;
                println!("Available skills ({})", skills.len());
                for s in &skills {
                    let skill = manager.load_skill(s)?;
                    println!("  {:<20} {}", skill.name, skill.description);
                }
            }
            SkillAction::Show { name } => {
                let manager = SkillManager::new(SkillManager::default_dir());
                let skill = manager.load_skill(&name)?;
                println!("Name:        {}", skill.name);
                println!("Description: {}", skill.description);
                println!("Version:     {}", skill.version);
                println!("Triggers:    {:?}", skill.trigger);
                println!("Steps:");
                for (i, step) in skill.steps.iter().enumerate() {
                    println!("  [{i}] {step:?}");
                }
            }
            SkillAction::Run { name, db } => {
                let db = resolve_db(db);
                let manager = SkillManager::new(SkillManager::default_dir());
                let skill = manager.load_skill(&name)?;
                let plan = manager.skill_to_plan(&skill);
                let (repo, agent) = build_engine(&db).await?;
                repo.save_plan(&plan).await?;
                info!(plan_id = %plan.id, skill = %name, "skill plan saved");
                print_plan_summary(&plan);
                execute_plan(&repo, &agent, &plan.id, None).await?;
            }
            SkillAction::InstallBuiltin => {
                SkillManager::install_builtin_skills()?;
                println!("Built-in skills installed successfully.");
            }
            SkillAction::Learn {
                plan_id,
                name,
                description,
                db,
            } => {
                let db = resolve_db(db);
                let repo = Arc::new(TaskRepo::new(&db)?);
                let plan = repo.load_plan(&plan_id).await?;
                let skill =
                    SkillManager::plan_to_skill(&plan, &name, &description);
                let manager = SkillManager::new(SkillManager::default_dir());
                manager.save_skill(&skill)?;
                println!(
                    "Learned skill '{}' from plan '{}' ({} steps)",
                    name,
                    plan.name,
                    skill.steps.len()
                );
            }
        },
        Commands::Demo { db } => {
            let db = resolve_db(db);
            let (repo, agent) = build_engine(&db).await?;

            let plan = Plan::new(
                "Demo Plan",
                vec![
                    think_step("Analyze the current project structure"),
                    tool_call_step(
                        "list_directory",
                        serde_json::json!({"path": "."}),
                    ),
                    think_step("Evaluate the directory listing results"),
                    wait_for_input_step("Do you want to continue with file reading?"),
                    tool_call_step(
                        "file_read",
                        serde_json::json!({"path": "Cargo.toml"}),
                    ),
                    think_step("Summarize findings from the Cargo.toml"),
                    tool_call_step(
                        "echo",
                        serde_json::json!({"message": "All steps completed successfully!"}),
                    ),
                    finish_step("Demo plan execution finished"),
                ],
            );

            repo.save_plan(&plan).await?;
            info!(plan_id = %plan.id, name = %plan.name, "demo plan saved");

            print_plan_summary(&plan);
            execute_plan(&repo, &agent, &plan.id, None).await?;
        }
        Commands::McpServer => {
            rupoo::mcp_server::run_mcp_server().await?;
        }
        Commands::Serve { db: _, port } => {
            println!("  {} Server mode (port {port}) — development only. Not for production use.", console::style("⚠").yellow());
            println!("  {} Must bind to 127.0.0.1 and add auth before exposing.", console::style("→").dim());
            #[cfg(feature = "gui")]
            {
                info!("system tray enabled");
                rupoo::tray::run_service();
            }
            #[cfg(not(feature = "gui"))]
            {
                info!("compile with --features gui for system tray support");
                tokio::signal::ctrl_c().await?;
            }
        }
        Commands::Status { short, db } => {
            let db = resolve_db(db);
            crate::cli::cmds::status::run(&db, short).await?;
        }
        Commands::Model { action, db } => {
            let db = resolve_db(db);
            crate::cli::cmds::model::run(&db, action).await?;
        }
        Commands::Session { action, db } => {
            let db = resolve_db(db);
            crate::cli::cmds::session::run(&db, action).await?;
        }
        Commands::Doctor { fix } => {
            crate::cli::cmds::doctor::run(fix).await?;
        }
        Commands::Logs { follow, lines, level, prev } => {
            crate::cli::cmds::logs::run(follow, lines, level.as_deref(), prev).await?;
        }
    }

    Ok(())
}

/// Resolve database path, defaulting to ~/.rupoo/agent.db.
fn resolve_db(db: Option<String>) -> String {
    db.unwrap_or_else(|| {
        tracing_setup::data_dir()
            .join("agent.db")
            .to_string_lossy()
            .to_string()
    })
}

// ---------------------------------------------------------------------------
// REPL — crossterm raw-mode interactive session
// ---------------------------------------------------------------------------

async fn run_repl() -> anyhow::Result<()> {
    let data_dir = tracing_setup::data_dir();
    std::fs::create_dir_all(&data_dir).ok();
    let db_path = data_dir.join("agent.db");

    let (repo, agent) = build_engine(db_path.to_str().unwrap_or("agent.db")).await?;
    let state = Arc::new(ReplState { repo, agent });

    let rt_handle = tokio::runtime::Handle::current();
    tokio::task::spawn_blocking(move || {
        run_repl_sync(state, rt_handle)
    }).await??;

    Ok(())
}

/// Synchronous REPL loop using crossterm raw mode for custom terminal input.
/// Prints a Claude Code-style 4-line prompt block each round.
fn run_repl_sync(
    state: Arc<ReplState>,
    rt_handle: tokio::runtime::Handle,
) -> anyhow::Result<()> {
    use crossterm::terminal::{enable_raw_mode, disable_raw_mode};
    use crossterm::event::{read, Event, KeyCode, KeyModifiers};
    use std::io::Write;

    let history_path = tracing_setup::data_dir().join("history.txt");
    let mut history: Vec<String> = Vec::new();

    // Load history
    if let Ok(content) = std::fs::read_to_string(&history_path) {
        history = content.lines().map(|l| l.to_string()).collect();
    }
    let mut history_index = history.len();

    // Banner
    println!();
    println!("  {}  Rupoo — AI Terminal Assistant", console::style("⚡").cyan());
    println!("  {}  /help for commands  ·  Ctrl+C to quit", console::style("─").dim());
    println!();

    // Session state
    struct ReplSession {
        total_tokens: u32,
        started_at: std::time::Instant,
        model_label: String,
    }

    let mut sess = ReplSession {
        total_tokens: 0,
        started_at: std::time::Instant::now(),
        model_label: {
            // Read current provider/model from DB
            let db = tracing_setup::data_dir().join("agent.db");
            let repo = rupoo::db::TaskRepo::new(db.to_str().unwrap_or("agent.db")).ok();
            match repo {
                Some(r) => {
                    let provider = rt_handle.block_on(r.get_setting("active_provider"))
                        .ok().flatten().unwrap_or_else(|| "none".into());
                    let model = rt_handle.block_on(r.get_setting(&format!("model.{provider}")))
                        .ok().flatten().unwrap_or_else(|| "default".into());
                    format!("{}/{}", provider, model)
                }
                None => "unknown".into(),
            }
        },
    };

    // Shortcuts carousel (8 items, 3s each)
    const SHORTCUTS: &[(&str, &str)] = &[
        ("/status", "view system health overview"),
        ("/model show", "check your current AI model"),
        ("/session list", "browse your past plans"),
        ("/doctor", "diagnose your environment"),
        ("/logs 10", "peek at recent agent logs"),
        ("/config set", "configure API keys & settings"),
        ("/help", "list all available commands"),
        ("/quit", "exit Rupoo"),
    ];

    fn current_shortcut() -> &'static (&'static str, &'static str) {
        let secs = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs();
        let idx = (secs / 3) as usize % SHORTCUTS.len();
        &SHORTCUTS[idx]
    }

    enable_raw_mode()?;

    // Character-by-character input reader with history navigation
    let read_input = |hist: &mut Vec<String>, hist_idx: &mut usize| -> std::io::Result<String> {
        let mut buf = String::new();
        let mut cursor = 0usize;

        loop {
            match read()? {
                Event::Key(ke) => match ke.code {
                    KeyCode::Char(c) if ke.modifiers == KeyModifiers::NONE || ke.modifiers == KeyModifiers::SHIFT => {
                        let ch = if ke.modifiers == KeyModifiers::SHIFT {
                            c.to_ascii_uppercase()
                        } else {
                            c
                        };
                        buf.insert(cursor, ch);
                        cursor += 1;
                        print!("\r\x1b[K> {}", buf);
                        if cursor < buf.len() {
                            print!("\x1b[{}D", (buf.len() - cursor) as u16);
                        }
                    }
                    KeyCode::Enter => {
                        let trimmed = buf.trim().to_string();
                        if !trimmed.is_empty() && hist.last().map(|l| l != &trimmed).unwrap_or(true) {
                            hist.push(trimmed.clone());
                        }
                        *hist_idx = hist.len();
                        println!();
                        return Ok(trimmed);
                    }
                    KeyCode::Backspace => {
                        if cursor > 0 {
                            buf.remove(cursor - 1);
                            cursor -= 1;
                            print!("\r\x1b[K> {}", buf);
                            if cursor < buf.len() {
                                print!("\x1b[{}D", (buf.len() - cursor) as u16);
                            }
                        }
                    }
                    KeyCode::Left => {
                        if cursor > 0 { cursor -= 1; print!("\x1b[1D"); }
                    }
                    KeyCode::Right => {
                        if cursor < buf.len() { cursor += 1; print!("\x1b[1C"); }
                    }
                    KeyCode::Up => {
                        if *hist_idx > 0 {
                            *hist_idx -= 1;
                            buf = hist[*hist_idx].clone();
                            cursor = buf.len();
                            print!("\r\x1b[K> {}", buf);
                        }
                    }
                    KeyCode::Down => {
                        if *hist_idx < hist.len() - 1 {
                            *hist_idx += 1;
                            buf = hist[*hist_idx].clone();
                            cursor = buf.len();
                            print!("\r\x1b[K> {}", buf);
                        } else {
                            *hist_idx = hist.len();
                            buf.clear();
                            cursor = 0;
                            print!("\r\x1b[K> ");
                        }
                    }
                    KeyCode::Home | KeyCode::Char('a') if ke.modifiers.contains(KeyModifiers::CONTROL) => {
                        if cursor > 0 { print!("\x1b[{}D", cursor as u16); cursor = 0; }
                    }
                    KeyCode::End | KeyCode::Char('e') if ke.modifiers.contains(KeyModifiers::CONTROL) => {
                        if cursor < buf.len() {
                            let right = (buf.len() - cursor) as u16;
                            print!("\x1b[{}C", right);
                            cursor = buf.len();
                        }
                    }
                    KeyCode::Char('c') if ke.modifiers.contains(KeyModifiers::CONTROL) => {
                        println!("^C");
                        return Ok(String::new());
                    }
                    KeyCode::Char('d') if ke.modifiers.contains(KeyModifiers::CONTROL) => {
                        if buf.is_empty() { return Ok(String::new()); }
                    }
                    KeyCode::Char('u') if ke.modifiers.contains(KeyModifiers::CONTROL) => {
                        buf.clear(); cursor = 0;
                        print!("\r\x1b[K> ");
                    }
                    KeyCode::Char('w') if ke.modifiers.contains(KeyModifiers::CONTROL) => {
                        if cursor > 0 {
                            let before = &buf[..cursor];
                            if let Some(i) = before[..before.len().saturating_sub(1)].rfind(' ') {
                                let keep = before[..=i].to_string();
                                let after: String = buf[cursor..].to_string();
                                cursor = keep.len();
                                buf = keep + &after;
                            } else {
                                let after: String = buf[cursor..].to_string();
                                buf = after;
                                cursor = 0;
                            }
                            print!("\r\x1b[K> {}", buf);
                            if cursor < buf.len() {
                                print!("\x1b[{}D", (buf.len() - cursor) as u16);
                            }
                        }
                    }
                    _ => {}
                },
                _ => {}
            }
            std::io::stdout().flush().ok();
        }
    };

    // Main REPL loop
    loop {
        let sc = current_shortcut();
        let elapsed = sess.started_at.elapsed();
        let elapsed_str = format!("{:02}:{:02}",
            elapsed.as_secs() / 60,
            elapsed.as_secs() % 60);
        let tok_str = if sess.total_tokens >= 1000 {
            format!("{:.1}k", sess.total_tokens as f64 / 1000.0)
        } else {
            format!("{}", sess.total_tokens)
        };
        let plan_count = rt_handle
            .block_on(state.repo.list_plans(1, 0))
            .map(|p| p.len())
            .unwrap_or(0);

        // 1. Separator line
        let dash = "─".repeat(60);
        println!("  {}", console::style(&dash).dim());

        // 2. User input line
        print!("> ");
        std::io::stdout().flush()?;

        let input = read_input(&mut history, &mut history_index)?;

        // 3. Separator line
        println!("  {}", console::style(&dash).dim());

        // 4. Status bar
        println!("  {} /{} — {}  {}  ● {} | {} tok | ⏱ {} | 📦 {} plans",
            console::style("⌘").dim(),
            console::style(sc.0).cyan(),
            console::style(sc.1).dim(),
            console::style("│").dim(),
            sess.model_label,
            tok_str,
            elapsed_str,
            plan_count,
        );

        // Exit commands
        if input == "/exit" || input == "/quit" || input == "exit" || input == "quit" {
            println!("{}", console::style("Bye!").dim());
            break;
        }

        // Handle empty input
        if input.is_empty() {
            continue;
        }

        // Dispatch command or NL
        if input.starts_with('/') {
            let result = match rt_handle.block_on(handle_cmd(&state, &input)) {
                Ok(out) => console::strip_ansi_codes(&out).to_string(),
                Err(e) => format!("Error: {e}"),
            };
            if !result.is_empty() {
                println!("{}\n", result);
            }
        } else {
            let mut prog = crate::cli::progress::StepProgress::new();
            let truncated: String = input.chars().take(40).collect();
            prog.start("□", &format!("Thinking about: {truncated}"));
            match rt_handle.block_on(execute_nl(&state, &input)) {
                Ok(out) => {
                    prog.complete();
                    if let Some(u) = state.agent.last_usage() {
                        sess.total_tokens += u.prompt_tokens + u.completion_tokens;
                        crate::cli::progress::StepProgress::token_badge(u.prompt_tokens, u.completion_tokens);
                    }
                    crate::cli::progress::StepProgress::separator();
                    crate::cli::progress::StepProgress::response(&out);
                }
                Err(e) => {
                    prog.fail(&e.to_string());
                }
            }
        }
    }

    // Save history + cleanup
    if let Ok(mut f) = std::fs::File::create(&history_path) {
        for line in &history {
            let _ = writeln!(f, "{}", line);
        }
    }
    disable_raw_mode()?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Execute a natural language query via the shared state
// ---------------------------------------------------------------------------

async fn execute_nl(state: &ReplState, text: &str) -> anyhow::Result<String> {
    let plan = Plan::new(
        &text.chars().take(40).collect::<String>(),
        vec![think_step(text)],
    );
    state.repo.save_plan(&plan).await?;

    let mut plan = match state.agent.resume(&plan.id).await? {
        Some(p) => p,
        None => return Ok(String::new()),
    };

    loop {
        match state.agent.run_next_step(&mut plan).await? {
            rupoo::agent::StepOutcome::Advanced => {
                if plan.current_step_index >= plan.steps.len() {
                    break;
                }
            }
            rupoo::agent::StepOutcome::Finished => break,
            rupoo::agent::StepOutcome::Failed(e) => return Ok(format!("Failed: {e}")),
            rupoo::agent::StepOutcome::WaitingForInput(p) => {
                return Ok(format!("Input needed: {p}"));
            }
        }
    }

    let output = plan.steps.first().and_then(|s| {
        if let rupoo::task::Step::Think { output, .. } = s {
            output.clone()
        } else {
            None
        }
    });

    Ok(output.unwrap_or_else(|| "(no output)".into()))
}

// ---------------------------------------------------------------------------
// Handle a slash command in the async context
// ---------------------------------------------------------------------------

async fn handle_cmd(state: &ReplState, cmd: &str) -> anyhow::Result<String> {
    use console::style;
    use std::fmt::Write as _;

    let parts: Vec<&str> = cmd.splitn(3, ' ').collect();
    let command = parts[0];
    let args = parts.get(1..).unwrap_or(&[]);

    match command {
        "/skills" | "/skill" => {
            let manager = SkillManager::new(SkillManager::default_dir());
            match args.first().copied().unwrap_or("list") {
                "list" => {
                    let skills = manager.list_skills()?;
                    if skills.is_empty() {
                        Ok("  ℹ No skills installed. Try '/skills install'".into())
                    } else {
                        let mut out = String::new();
                        let _ = writeln!(out, "\n  Skills ({total}):", total = skills.len());
                        for s in &skills {
                            match manager.load_skill(s) {
                                Ok(skill) => {
                                    let _ = writeln!(out, "  ⚡ {:<20} {}",
                                        style(&skill.name).green(), skill.description);
                                }
                                Err(_) => {
                                    let _ = writeln!(out, "  {s}");
                                }
                            }
                        }
                        Ok(out)
                    }
                }
                "install" => {
                    SkillManager::install_builtin_skills()?;
                    Ok("  ✓ Built-in skills installed.".into())
                }
                other => {
                    Ok(format!("  ✗ Unknown: {other}. Try: list, install"))
                }
            }
        }
        "/config" => {
            match args.first().copied().unwrap_or("list") {
                "list" => {
                    let settings = state.repo.list_settings().await?;
                    if settings.is_empty() {
                        Ok("  ℹ No configuration set. Use: config set <key> <value>".into())
                    } else {
                        let mut out = String::new();
                        let _ = writeln!(out, "\n  Configuration:");
                        for (k, v) in &settings {
                            let display = if k.starts_with("api_key") {
                                format!("{}...", style(&v[..v.len().min(8)]).dim())
                            } else {
                                v.clone()
                            };
                            let _ = writeln!(out, "  {:<25} {}", style(k).cyan(), display);
                        }
                        Ok(out)
                    }
                }
                _ => Ok("  Usage: /config list".into()),
            }
        }
        "/git" => {
            match args.first().copied().unwrap_or("status") {
                "status" => {
                    match rupoo::git::GitRepo::open(".") {
                        Ok(git) => {
                            let branch = git.current_branch().unwrap_or_default();
                            let statuses = git.status()?;
                            let mut out = String::new();
                            let _ = writeln!(out, "\n  Branch: {}", style(branch).green());
                            if statuses.is_empty() {
                                let _ = writeln!(out, "  {} Clean working tree.", style("✓").green());
                            } else {
                                for s in &statuses {
                                    let color = if s.status.contains("modified") || s.status.contains("deleted") {
                                        style(&s.status).yellow()
                                    } else {
                                        style(&s.status).dim()
                                    };
                                    let _ = writeln!(out, "  {}  [{}]", style(&s.path).bold(), color);
                                }
                            }
                            Ok(out)
                        }
                        Err(e) => Ok(format!("  {} {}", style("✗").red(), e)),
                    }
                }
                _ => Ok("  Usage: /git status".into()),
            }
        }
        "/status" | "/st" => {
            let db = tracing_setup::data_dir().join("agent.db");
            crate::cli::cmds::status::output(db.to_str().unwrap_or("agent.db"), false).await
        }
        "/model" => {
            let db = tracing_setup::data_dir().join("agent.db");
            match args.first().copied().unwrap_or("show") {
                "show" => {
                    crate::cli::cmds::model::output(
                        db.to_str().unwrap_or("agent.db"),
                        Some(ModelAction::Show),
                    ).await
                }
                "list" => {
                    crate::cli::cmds::model::output(
                        db.to_str().unwrap_or("agent.db"),
                        Some(ModelAction::List),
                    ).await
                }
                "set" => {
                    let target = args.get(1).copied().map(|s| s.to_string());
                    crate::cli::cmds::model::output(
                        db.to_str().unwrap_or("agent.db"),
                        Some(ModelAction::Set { target }),
                    ).await
                }
                _ => Ok("  Usage: /model [show|list|set <provider>]".into()),
            }
        }
        "/session" | "/s" | "/plans" => {
            let db = tracing_setup::data_dir().join("agent.db");
            match args.first().copied().unwrap_or("list") {
                "list" => {
                    let limit = args.get(1)
                        .and_then(|s| s.parse::<usize>().ok())
                        .unwrap_or(10);
                    crate::cli::cmds::session::output(
                        db.to_str().unwrap_or("agent.db"),
                        SessionAction::List { limit },
                    ).await
                }
                "show" => {
                    let id = args.get(1).unwrap_or(&"").to_string();
                    crate::cli::cmds::session::output(
                        db.to_str().unwrap_or("agent.db"),
                        SessionAction::Show { id },
                    ).await
                }
                "delete" => {
                    let id = args.get(1).unwrap_or(&"").to_string();
                    crate::cli::cmds::session::output(
                        db.to_str().unwrap_or("agent.db"),
                        SessionAction::Delete { id },
                    ).await
                }
                "prune" => {
                    let days = args.get(1)
                        .and_then(|s| s.parse::<u64>().ok())
                        .unwrap_or(30);
                    crate::cli::cmds::session::output(
                        db.to_str().unwrap_or("agent.db"),
                        SessionAction::Prune { days },
                    ).await
                }
                _ => Ok("  Usage: /session [list|show <id>|delete <id>|prune [days]]".into()),
            }
        }
        "/doctor" | "/diag" => {
            crate::cli::cmds::doctor::output(true).await
        }
        "/logs" | "/log" => {
            let lines = args.first()
                .and_then(|s| s.parse::<usize>().ok())
                .unwrap_or(50);
            let level = args.get(1).copied();
            crate::cli::cmds::logs::output(false, lines, level, false).await
        }
        _ => Ok(format!("  {} Unknown: {}. Try /help", style("?").yellow(), cmd)),
    }
}

// ---------------------------------------------------------------------------
// Shared helpers (unchanged from previous version)
// ---------------------------------------------------------------------------

async fn build_engine(db_path: &str) -> anyhow::Result<(Arc<TaskRepo>, Agent)> {
    let repo = Arc::new(TaskRepo::new(db_path)?);
    let tool_executor = Box::new(McpToolExecutor::with_defaults());
    let mut agent = Agent::new(Arc::clone(&repo), tool_executor);

    if let Some(api_key) = repo.get_setting("api_key.anthropic").await? {
        let mut cfg = rupoo::llm::LlmConfig::new(
            rupoo::llm::LlmProvider::Anthropic,
            Some(api_key),
        );
        if let Some(model) = repo.get_setting("model.anthropic").await? {
            cfg.model = model;
        }
        agent = agent.with_llm(rupoo::llm::LlmGateway::new(cfg));
        info!("Anthropic LLM configured");
    } else if let Some(api_key) = repo.get_setting("api_key.openai").await? {
        let mut cfg = rupoo::llm::LlmConfig::new(
            rupoo::llm::LlmProvider::OpenAI,
            Some(api_key),
        );
        if let Some(model) = repo.get_setting("model.openai").await? {
            cfg.model = model;
        }
        if let Some(base_url) = repo.get_setting("base_url.openai").await? {
            cfg.base_url = Some(base_url);
        }
        agent = agent.with_llm(rupoo::llm::LlmGateway::new(cfg));
        info!("OpenAI-compatible LLM configured");
    } else {
        info!("no LLM configured, using dummy think output");
    }

    Ok((repo, agent))
}

async fn execute_plan(
    _repo: &Arc<TaskRepo>,
    agent: &Agent,
    plan_id: &str,
    input: Option<&str>,
) -> anyhow::Result<()> {
    info!(plan_id = %plan_id, "starting/resuming plan");

    let mut plan = match agent.resume(plan_id).await? {
        Some(p) => p,
        None => {
            info!("plan already completed, nothing to do");
            return Ok(());
        }
    };

    info!(
        plan_id = %plan_id,
        status = ?plan.status,
        current_step = plan.current_step_index,
        total_steps = plan.steps.len(),
        "plan loaded"
    );

    loop {
        let step_index = plan.current_step_index;

        if let Some(input_val) = input {
            let is_waiting = plan.steps.get(step_index).is_some_and(|s| s.is_waiting());
            if is_waiting {
                info!(plan_id = %plan_id, step = step_index, input = %input_val, "injecting input into WaitForInput step");
                let outcome = agent.inject_input(&mut plan, step_index, input_val).await?;
                match outcome {
                    rupoo::agent::StepOutcome::Advanced => {
                        info!(plan_id = %plan_id, step = step_index, "input injected, step completed");
                        continue;
                    }
                    _ => {
                        anyhow::bail!("unexpected outcome from inject_input: {:?}", outcome);
                    }
                }
            }
        }

        let outcome = agent.run_next_step(&mut plan).await?;

        match outcome {
            rupoo::agent::StepOutcome::Advanced => {
                info!(
                    plan_id = %plan_id,
                    step = step_index,
                    "step completed"
                );
            }
            rupoo::agent::StepOutcome::Finished => {
                info!(plan_id = %plan_id, "plan execution finished");
                print_plan_result(&plan);
                break;
            }
            rupoo::agent::StepOutcome::WaitingForInput(prompt) => {
                println!("\n=== WAITING FOR INPUT ===");
                println!("Prompt: {prompt}");
                println!("==========================");
                if input.is_some() {
                    println!("Input was provided but the step type was not WaitForInput at resume time.");
                } else {
                    println!("The plan is paused. Re-run with `--input <text>` to provide input.");
                }
                break;
            }
            rupoo::agent::StepOutcome::Failed(err) => {
                println!("\n=== PLAN FAILED ===");
                println!("Error: {err}");
                println!("====================\n");
                break;
            }
        }
    }

    Ok(())
}

fn print_plan_summary(plan: &Plan) {
    println!("\n=== PLAN: {} ===", plan.name);
    println!("ID: {}", plan.id);
    println!("Steps:");
    for (i, step) in plan.steps.iter().enumerate() {
        let label = match step {
            rupoo::task::Step::Think { instruction, .. } => format!("THINK: {instruction}"),
            rupoo::task::Step::ToolCall { tool_name, params, .. } => {
                format!("TOOL: {tool_name} ({})", params)
            }
            rupoo::task::Step::WaitForInput { prompt, .. } => format!("WAIT: {prompt}"),
            rupoo::task::Step::Finish { summary, .. } => format!("FINISH: {summary}"),
            rupoo::task::Step::Exec { command, .. } => format!("EXEC: {command}"),
            rupoo::task::Step::HttpRequest { url, method, .. } => format!("HTTP: {method:?} {url}"),
            rupoo::task::Step::BrowserAction { action, .. } => format!("BROWSER: {action:?}"),
        };
        println!("  [{i}] {label}");
    }
    println!("==========================\n");
}

fn print_plan_result(plan: &Plan) {
    println!("\n=== PLAN RESULT ===");
    println!("Name: {}", plan.name);
    println!("Status: {:?}", plan.status);
    for (i, step) in plan.steps.iter().enumerate() {
        let status_mark = match step.status() {
            rupoo::task::StepStatus::Completed => "✓",
            rupoo::task::StepStatus::Failed => "✗",
            rupoo::task::StepStatus::Running => "▶",
            rupoo::task::StepStatus::Pending => "·",
            rupoo::task::StepStatus::WaitingForInput => "⊘",
        };

        let label = match step {
            rupoo::task::Step::Think { instruction, output, .. } => {
                format!("THINK: {instruction} | out: {}", output.as_deref().unwrap_or("-"))
            }
            rupoo::task::Step::ToolCall { tool_name, result, .. } => {
                let r = result
                    .as_ref()
                    .map(|v| v.to_string())
                    .unwrap_or_else(|| "-".to_string());
                format!("TOOL: {tool_name} | result: {r}")
            }
            rupoo::task::Step::WaitForInput { prompt, response, .. } => {
                format!("WAIT: {prompt} | response: {}", response.as_deref().unwrap_or("(pending)"))
            }
            rupoo::task::Step::Finish { summary, .. } => format!("FINISH: {summary}"),
            rupoo::task::Step::Exec { command, output, .. } => {
                format!("EXEC: {command} | out: {}", output.as_deref().unwrap_or("-"))
            }
            rupoo::task::Step::HttpRequest { url, response, .. } => {
                format!("HTTP: {url} | resp: {}", response.as_deref().unwrap_or("-"))
            }
            rupoo::task::Step::BrowserAction { action, output, .. } => {
                format!("BROWSER: {action:?} | out: {}", output.as_deref().unwrap_or("-"))
            }
        };
        println!("  {status_mark} [{i}] {label}");
    }
    println!("========================\n");
}

#[cfg(feature = "gui")]
fn launch_gui(db_path: &str) -> anyhow::Result<()> {
    let state = rupoo::gui::AppState::new(db_path)?;
    let app = rupoo::gui::GuiApp::new(state);
    let native_options = eframe::NativeOptions::default();
    eframe::run_native(
        "Yupoo",
        native_options,
        Box::new(move |_cc| Box::new(app)),
    )
    .map_err(|e| anyhow::anyhow!("GUI error: {e}"))
}
